# name of the software
name: PSA Documentation


description: PSA documentation website
baseurl: "/opa00/opa-Documentation-AppDevelopper" # the subpath of the site, e.g. /blog
url: "https://pages.github.psa-cloud.com" # the base hostname & protocol for the site, e.g. http://example.com

permalink: pretty
exclude: ["node_modules/", "*.gemspec", "*.gem", "Gemfile", "Gemfile.lock", "package.json", "package-lock.json",  "script/", "LICENSE.txt", "lib/", "bin/", "README.md", "Rakefile"]


theme: jekyll-bulma

# Enable or disable the site search
search_enabled: false

collections:
  - headunit-sdk
  - webPortal_QuickGuides
collections:
  headunit-sdk:
    output: true
  webPortal_QuickGuides:
    output: true
  webPortal_TutorialsAdvanced:
    output: true

links:
    header:
    footer:

ui:
    header:
        color1: "#080331"
        color2: "#673051"

social:


analytics:

# Build settings
markdown: kramdown
